<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            ['id' => 30, 'hr_id' => 27, 'name' => 'Rasana', 'email' => 'vsana_56@yahoo.in', 'phone' => '7977675042', 'current_ctc' => '2500000', 'expected_ctc' => '300000', 'skills' => 'software development, ASP.NET, .NET Core,HTML, CSS, JavaScript, jQuery', 'location' => 'Mumbai, Maharashtra, India', 'job_type' => 'Remote', 'experience' => 5, 'notice_period' => 'Immediate Joiner', 'note' => null, 'resume' => 'resumes/GgCmbJXzjkEzCiKAHQjEiRRoKHbIpC3tTP8psa2R.pdf', 'company_resume' => 'company_resumes/Gelu41eoqWVXB2vS2aLqxtPHAD19VfWxc1TjECT7.pdf', 'created_at' => '2025-09-26 17:57:12', 'updated_at' => '2026-02-11 12:26:49', 'last_updated_by' => null, 'is_highlighted' => 0],
            ['id' => 31, 'hr_id' => 27, 'name' => 'Sarthak Jain', 'email' => 'sarthak.jain0506@gmail.com', 'phone' => '8630750189', 'current_ctc' => '700000', 'expected_ctc' => '100000', 'skills' => 'software engineer, C#, SQL, JavaScript, HTML, CSS, Framework and Libraries: .ASP.NET, .NET Core, Entity Framework, LINQ, Kendo UI', 'location' => 'Saharanpur, Uttar Pradesh', 'job_type' => 'Remote', 'experience' => 4, 'notice_period' => 'Immediate Joiner', 'note' => null, 'resume' => 'resumes/NGew0ydwkn0Wd2lkcf21oMGphY5b7Jww4hG71TBK.pdf', 'company_resume' => 'company_resumes/5cMA5vdTT0Zg7vX3bfkGbZWsXrFC2iSNWCXju9Xs.pdf', 'created_at' => '2025-09-27 12:01:17', 'updated_at' => '2026-02-11 12:24:46', 'last_updated_by' => null, 'is_highlighted' => 0],
            ['id' => 32, 'hr_id' => 27, 'name' => 'shraddha tapase', 'email' => 'shraddha.tapase18@gmail.com', 'phone' => '7020084906', 'current_ctc' => '600000', 'expected_ctc' => '700000', 'skills' => 'laravel Developer, mysql, html, css, bootstrap, Mysql, php , Git,, VS Code', 'location' => 'Mumbai ,Maharashtra', 'job_type' => 'Remote', 'experience' => 2, 'notice_period' => 'Immediate Joiner', 'note' => null, 'resume' => 'resumes/LhSFkvopYnorcb9C2ntpGmNA55y3aD5gqzoTi5bo.pdf', 'company_resume' => 'company_resumes/aBc1vlMpKJ4zWVuzFkObozJ9YvCMUVTrrSGNXBjv.pdf', 'created_at' => '2025-09-27 12:22:41', 'updated_at' => '2026-02-13 13:27:03', 'last_updated_by' => null, 'is_highlighted' => 0],
            ['id' => 33, 'hr_id' => 27, 'name' => 'Anuj Kumar verma', 'email' => 'anujve870@gmail.com', 'phone' => '7458057269', 'current_ctc' => '500000', 'expected_ctc' => '600000', 'skills' => 'Software Developer, Laravel, MySQL . Web Designing : HTML5, CSS3 . Scripting Languages : Javascript, JQuery, Ajax .', 'location' => 'Lucknow', 'job_type' => 'Remote', 'experience' => 2, 'notice_period' => 'Immediate Joiner', 'note' => null, 'resume' => 'resumes/4zrh2JIoVs8dwGobVWTTN5fWPduTXd15IcuV1SDW.pdf', 'company_resume' => 'company_resumes/3urSrN5BxIrv3Ldm6LQwFvWqWv5zShmGaF5h27We.pdf', 'created_at' => '2025-09-27 13:25:05', 'updated_at' => '2026-02-11 13:25:41', 'last_updated_by' => null, 'is_highlighted' => 0],
            ['id' => 34, 'hr_id' => 27, 'name' => 'Premadeepthi KS', 'email' => 'subramanideepusr@gmail.com', 'phone' => '9600166149', 'current_ctc' => '240000', 'expected_ctc' => '320000', 'skills' => 'Backend Developer , PHP, Larave, JSON & Postman, HTML, CSS, JavaScript, React.js', 'location' => 'West Saidapet', 'job_type' => 'Remote', 'experience' => 2, 'notice_period' => 'Immediate Joiner', 'note' => null, 'resume' => 'resumes/U1LKKAoAyv7f1ZBSj0pxUbJWALVRvhGpIjZJUbDi.pdf', 'company_resume' => 'company_resumes/NdtN6kvIgDISHQipLyJxJfTAEOFfcmiXAtLcH3j6.pdf', 'created_at' => '2025-09-27 13:31:57', 'updated_at' => '2026-02-11 13:17:24', 'last_updated_by' => null, 'is_highlighted' => 0],
            ['id' => 35, 'hr_id' => 27, 'name' => 'Prakash Ranjan Mohanty', 'email' => 'prakash.mohanty@gmail.com', 'phone' => '9740658250', 'current_ctc' => '1200000', 'expected_ctc' => '1500000', 'skills' => 'PHP Developer, JavaScript, ASP,JSP, ASP.Net ,C#, HTML, CSS, XML,Android Studio, Github', 'location' => 'Bengaluru', 'job_type' => 'Remote', 'experience' => 2, 'notice_period' => 'Immediate Joiner', 'note' => null, 'resume' => 'resumes/LbaZkSoZ6oG4oLL5omr4sGygxs81CNF2ycu7bu90.pdf', 'company_resume' => 'company_resumes/CivezGhfp0Yse1hbE53yr4LX2zYaViAX1Ow7ANkv.pdf', 'created_at' => '2025-09-27 14:19:47', 'updated_at' => '2026-02-11 13:13:28', 'last_updated_by' => null, 'is_highlighted' => 0],
            ['id' => 36, 'hr_id' => 27, 'name' => 'Shriram', 'email' => 'shriramkumar010@gmail.com', 'phone' => '8294755720', 'current_ctc' => '400000', 'expected_ctc' => '600000', 'skills' => 'SOFTWARE DEVELOPER , Laravel Filament Symfony System Design Design patter', 'location' => 'Chandigarh', 'job_type' => 'Remote', 'experience' => 3, 'notice_period' => '15 Days', 'note' => null, 'resume' => 'resumes/i1Is8kGWiyL7Ae81x8dYyI9v6XAG7s3rgDPBzCiD.pdf', 'company_resume' => 'company_resumes/qy0G0PZmOKCndmQahZrGKx81YxFjFwq1h2HD0AnJ.pdf', 'created_at' => '2025-09-27 14:30:00', 'updated_at' => '2026-02-11 13:05:07', 'last_updated_by' => null, 'is_highlighted' => 0],
            ['id' => 37, 'hr_id' => 27, 'name' => 'Savari Irudaya Raj.X', 'email' => 'irudayan111@gmail.com', 'phone' => '8760870314', 'current_ctc' => '360000', 'expected_ctc' => '400000', 'skills' => 'Software Developer ,PHP Frameworks Larevel, Wordpress, MVC model Web Technologies web services, HTML, CSS,Visual Studio Code', 'location' => 'Visuvasampatti (vill)', 'job_type' => 'Remote', 'experience' => 3, 'notice_period' => 'Immediate Joiner', 'note' => null, 'resume' => 'resumes/OiQAgAg4uxnl95BU8NDydqJkbJzlEM6yJoLBQ66c.pdf', 'company_resume' => 'company_resumes/G1lXjRnNyQkNGLNr6YKRR5Fe5aasKr80FFt9BDLC.pdf', 'created_at' => '2025-09-27 14:58:36', 'updated_at' => '2026-02-11 13:03:19', 'last_updated_by' => null, 'is_highlighted' => 0],
            ['id' => 38, 'hr_id' => 27, 'name' => 'shraddha kabade', 'email' => 'shraddha2kabade@gmail.com', 'phone' => '7057751168', 'current_ctc' => '400000', 'expected_ctc' => '500000', 'skills' => 'PHP Developer, JavaScript, HTML, CSS, bootstrap,jQuery,laravel,Laravel, Vtiger', 'location' => 'Miraj, Maharashtra', 'job_type' => 'Remote', 'experience' => 3, 'notice_period' => 'Immediate Joiner', 'note' => null, 'resume' => 'resumes/REsurXHkqGXRMHt66BL3noRqcP8jXGZk2SNbY9v6.pdf', 'company_resume' => 'company_resumes/YHXm7VECmwx5uSIzPPGZPVJ9fecngQbS4m7FkT9H.pdf', 'created_at' => '2025-09-27 15:10:57', 'updated_at' => '2026-02-11 12:59:16', 'last_updated_by' => null, 'is_highlighted' => 0],
            ['id' => 39, 'hr_id' => 27, 'name' => 'Anurag aswal', 'email' => 'anuragaswal222@gmail.com', 'phone' => '8755607995', 'current_ctc' => '224000', 'expected_ctc' => '300000', 'skills' => 'Software Developer, WordPress, HTML, CSS, Laravel, MySQL, JavaScript, HTML', 'location' => 'Rishikesh', 'job_type' => 'Remote', 'experience' => 1, 'notice_period' => 'Immediate Joiner', 'note' => null, 'resume' => 'resumes/98tr1QbfkUGAcuukSYYeL5g1DPQGnGZEZbMxOGSN.pdf', 'company_resume' => 'company_resumes/yN67qzCxgHSL5w7wwTfAQFXVnSP0Yd3ldnqWbOPX.pdf', 'created_at' => '2025-09-27 15:21:54', 'updated_at' => '2026-02-11 12:35:34', 'last_updated_by' => null, 'is_highlighted' => 0],
            ['id' => 40, 'hr_id' => 27, 'name' => 'Ashutosh Chauhan', 'email' => 'ashutoshchauhan129@gmail.com', 'phone' => '8468921900', 'current_ctc' => '715000', 'expected_ctc' => '800000', 'skills' => 'Software Developer, PHP, Laravel, CodeIgniter, Lumen o Frontend: HTML/CSS, JavaScript, jQuery, Ajax, Vue.js', 'location' => 'Faridabad, Haryana', 'job_type' => 'Remote', 'experience' => 3, 'notice_period' => '30 Days', 'note' => null, 'resume' => 'resumes/gnqNGUJYObMNR8kmPVZgrJqWDdiOB1ygqZeqkGcF.pdf', 'company_resume' => 'company_resumes/EJZSaMC1jiYBsOcC7qIvnTM3UuWoPo0Bt2s4J7kE.pdf', 'created_at' => '2025-09-27 16:07:22', 'updated_at' => '2026-02-11 12:32:21', 'last_updated_by' => null, 'is_highlighted' => 0],
        ];

        DB::table('students')->insert($students);
    }
}
